apiVersion: v1
kind: Endpoints
metadata:
  name: sample
  namespace: test
  annotations:
    argocd.argoproj.io/sync-options: Validate=false
subsets:
  - addresses:
      - ip: 192.168.90.203
    ports:
      - port: 1
  - addresses:
      - ip: 192.168.90.201
    ports:
      - port: 1
  - addresses:
      - ip: 192.168.90.202
    ports:
      - port: 1
