apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: secret-reader
  ownerReferences:
    - apiVersion: pipelines.openshift.io/v1alpha1
      kind: GitopsService
      name: gitopsservice-sample
      uid: 07ee92ae-f2bf-430d-a593-60f56fc664b9
rules:
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["get", "watch", "list"]
