# apiVersion: rbac.authorization.k8s.io/v1
# kind: ClusterRole
# metadata:
#   name: secret-reader
#   ownerReferences:
#     - apiVersion: pipelines.openshift.io/v1alpha1
#       kind: GitopsService
#       name: gitopsservice-sample
#       uid: 5b845742-0cda-41ce-aa29-473895878d64
# rules:
# - apiGroups: [""]
#   resources: ["secrets"]
#   verbs: ["get", "watch", "list"]
