apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: pod-reader
  # namespace: argocd
  ownerReferences:
    - apiVersion: pipelines.openshift.io/v1alpha1
      kind: GitopsService
      name: gitopsservice-sample
      uid: 5b845742-0cda-41ce-aa29-473895878d64
rules:
- apiGroups: [""] # "" indicates the core API group
  resources: ["pods"]
  verbs: ["get", "watch", "list"]
