apiVersion: v1
kind: ServiceAccount
metadata:
  name: sample
  namespace: test
  ownerReferences:
    - apiVersion: rbac.authorization.k8s.io/v1
      kind: ClusterRole
      name: secret-reader
      uid: 7436bbbb-b55c-485f-a0d5-008ab475b7da
